before:
  hooks:
    - go generate ./...
builds:
- id: gorpa
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/bhojpur/gorpa/pkg/gorpa.Version={{.Version}}-{{.ShortCommit}}
archives:
- id: gorpa
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  builds:
  - gorpa
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/bhojpur/gorpa:{{ .Tag }}"
    extra_files:
    - README.md
