version: "3"

vars:
  GREETING: Hello, Bhojpur GoRPA Developer!

tasks:
    default:
        cmds:
        - echo "{{.GREETING}}"
        silent: true

    build-tools:
        desc: Build the software tools
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/gorpa main.go 
        - chmod 755 bin/gorpa
        - cp bin/gorpa $GOPATH/bin

    build-desktop:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -name "Bhojpur GoRPA" -os macos -icon gorpa.png
        - guiutl package -name "Bhojpur GoRPA" -os linux -icon gorpa.png
        - guiutl package -name "Bhojpur GoRPA" -os windows -icon gorpa.png

    package-android:
        desc: Package the mobile application for Android
        cmds:
        - guiutl package -name "Bhojpur GoRPA" -os android -appID net.bhojpur.gorpa -icon gorpa.png

    package-ios:
        desc: Package the mobile application for iOS
        cmds:
        - guiutl package -name "Bhojpur GoRPA" -os ios -appID net.bhojpur.gorpa -icon gorpa.png

    release-macos:
        desc: Release the native application for macOS App Store
        cmds:
        - guiutl release -appID net.bhojpur.gorpa -appVersion 1.0 -appBuild 1 -category business

    release-android:
        desc: Release the mobile application for Google Play
        cmds:
        - guiutl release -os android -appID net.bhojpur.gorpa -appVersion 1.0 -appBuild 1

    release-ios:
        desc: Release the mobile application for iOS App Store
        cmds:
        - guiutl release -os ios -appID net.bhojpur.gorpa -appVersion 1.0 -appBuild 1

    run-web-server:
        desc: Run the web server application from source code
        cmds:
        - GOFLAGS=-mod=mod go run server.go
 
    run-web-client:
        desc: Run the web client application from source code
        cmds:
        - GOFLAGS=-mod=mod go run client.go

    run-mobile:
        desc: Run the mobile client application on emulator
        cmds:
        - GOFLAGS=-mod=mod go run -tags mobile native/main.go

    run-desktop: 
        desc: Run the desktop application on local host
        cmds:
        - GOFLAGS=-mod=mod go run native/main.go

    generate:
        desc: Generate Go source code from Protool Buffers
        cmds:
        - GOFLAGS=-mod=mod go generate ./...

    test:
        desc: Execute all the Unit Tests
        cmds:
        - gotestsum --junitfile test-results/unit-tests.xml -- -short -race -cover -coverprofile test-results/cover.out ./...

    swagger.gen:
        desc: Generate Go code
        cmds:
        - GOFLAGS=-mod=mod go generate bhojpur.net/gorpa/internal bhojpur.net/gorpa/pkg/swagger

    swagger.validate:
        desc: Validate all the Swagger API specifications
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Generate documentation for Swagger specified APIs
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html
